site_name: Lailai的学习主页

theme:
  language: zh 
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/492738377
      name: 牛_奶奶
